app/twitter/__init__.py
from flask import Blueprint

bp = Blueprint('twitter', __name__, url_prefix='/twitter')

from app.twitter import routes

app/twitter/routes.py
from app.twitter import bp
from flask import (
    render_template,
    redirect,
    url_for,
    request,
    flash,
    current_app
)
from app.utils.twitter_utils import (
    send_tweet,
    send_media_tweet,
    update_twitter_image,
    update_twitter_background_image
)
from app.utils.meta_utils import _process_request_file


@bp.route('/compose', methods=("POST",))
def compose():
    """
    View function to return a form where a user can fill out a tweet
    and a invoice to be paid to send the tweet
    """
    if request.method == 'POST':
        # Create the tweet and send it
        media_tweet = False
        tweet_content = request.form.get("title")
        success, upload, unique_filename = _process_request_file(request)
        if not success:
            flash(current_app.config['FILE_TYPE_UNSUPPORTED'])
            return redirect(url_for('twitter.compose'))
        if upload is not None:
            media_tweet = True
        if media_tweet:
            response = send_media_tweet(unique_filename, tweet_content)
        else:
            response = send_tweet(tweet_content)
        if response == "Success":
            flash("Tweet sent!")
        else:
            flash(response)
        return redirect(url_for('bombadillo.lightning'))
    return render_template('twitter/compose.html')


@bp.route('/update_profile_picture', methods=("POST",))
def update_profile_picture():
    """
    View function to return a form where a user can upload a picture to update
    the profile picture of the twitter account
    """
    if request.method == 'POST':
        success, upload, unique_filename = _process_request_file(request)
        if not success:
            flash(current_app.config['FILE_TYPE_UNSUPPORTED'])
            return redirect(url_for('bombadillo.lightning'))
        response = update_twitter_image(unique_filename)
        if response is None:
            flash("Profile picture updated!")
        else:
            flash(response)
        return redirect(url_for('bombadillo.lightning'))
    return render_template('twitter/update_profile_image.html')


@bp.route('/update_background_picture', methods=("POST",))
def update_background_picture():
    """
    View function to return a form where a user can upload a picture to update
    the background picture of the twitter account
    """
    if request.method == 'POST':
        success, upload, unique_filename = _process_request_file(request)
        if not success:
            flash(current_app.config['FILE_TYPE_UNSUPPORTED'])
            return redirect(url_for('bombadillo.lightning'))
        response = update_twitter_background_image(unique_filename)
        if response is None:
            flash("Banner picture updated!")
        else:
            flash(response)
        return redirect(url_for('bombadillo.lightning'))
    return render_template('twitter/update_background_image.html')

app/templates/twitter/_advertisement_card.html
<div class="card">
    {% if request.endpoint == 'bombadillo.post' %}
        {% include 'bombadillo/_explore_card_content.html' %}
    {% else %}
        <a href="{{ url_for('bombadillo.post', post_code=post.post_code) }}">
            {% include 'bombadillo/_explore_card_content.html' %}
        </a>
    {% endif %}
    <div class="card-body">
        {% if not post.meme %}
            <p class="card-text">
                {{ post.title }}
            </p>
        {% endif %}
        {% include '_advertisement_button_actions.html' %}
        {% include 'bombadillo/_thread_lightning_boost.html' %}
    </div>
</div>

app/templates/twitter/compose.html
{% extends 'base.html' %}

{% block header %}
<h4 class="header-title">{% block title %}tweet on @junkbite_tweets timeline.{% endblock %}</h4>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <form id="invoice-form" action="{{ url_for('twitter.compose') }}" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="body">Text</label>
                <textarea class="form-control" name="body" id="create-body" autocomplete=off onkeyup="copyTextToMeme(this.value)">{{ request.form['body'] }}</textarea>
            </div>
            <div class="form-group">
                <label for="file">Image</label>
                <input type="file" class="form-control-file" name="file" id="getval"/>
            </div>
        </form>
        <input class="btn btn-primary" role="button" value="Submit" onclick="getGeneralInvoice()">
        <hr>
        <div class="form-group pl-0">
            <h3>Preview</h3>
            <div class="card">
                <div class="card-body" id="top-text-preview">
                    <p id="meme-text" class="card-text"></p>
                </div>
                {% include '_image_display_in_form.html' %}
            </div>
        </div>
    </div>
    <div class="col-sm twitter-feed-scroll">
        <a class="twitter-timeline" href="https://twitter.com/junkbite_tweets?ref_src=twsrc%5Etfw">Tweets by junkbite_tweets</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
    </div>
</div>
{{ modal_invoice() }}
{% endblock %}

app/templates/twitter/update_background_image.html
{% extends 'base.html' %}

{% block header %}
<h4 class="header-title">{% block title %}Update @junkbite_tweets' background picture for sats{% endblock %}</h4>
{% endblock %}

{% block content %}
<div id=create_div>
    <form action="{{ url_for('twitter.update_background_picture') }}" method=post enctype="multipart/form-data"
        class=add-post id='tweet-form'>
        <div class=post-text>
            <input type='file' name='file' id='getval' required /><br>
            <div id=tiles-img-container class=tiles-column>
                <div id=img-post>
                    <p id='meme-text' style="text-align: left;"></p>
                </div>
                <div id='show-image'>
                    <video style="display: none;" id='load-video' controls autoplay muted loop>
                        <source id=source-me type='video/mp4'>
                    </video>
                    <img style="display: none;" id='load-img' alt="" />
                </div>
            </div><br>
        </div><br>
    </form>
</div>
<div>
    <button class="btn btn-primary"onclick="getGeneralInvoice()">Update Background Picture</button>
</div>
{% endblock %}

app/templates/twitter/update_profile_image.html
{% extends 'base.html' %}

{% block header %}
<h4 class="header-title">{% block title %}Update @junkbite_tweets' profile picture for sats{% endblock %}</h4>
{% endblock %}

{% block content %}
<div id=create_div>
    <form action="{{ url_for('twitter.update_profile_picture') }}" method=post enctype="multipart/form-data"
        class=add-post id='tweet-form'>
        <div class=post-text>
            <input type='file' name='file' id='getval' required /><br>
            <div id=tiles-img-container class=tiles-column>
                <div id=img-post>
                    <p id='meme-text' style="text-align: left;"></p>
                </div>
                <div id='show-image'>
                    <video style="display: none;" id='load-video' controls autoplay muted loop>
                        <source id=source-me type='video/mp4'>
                    </video>
                    <img style="display: none;" id='load-img' alt="" />
                </div>
            </div><br>
        </div><br>
    </form>
</div>
<div>
    <button class="btn btn-primary"onclick="getGeneralInvoice()">Update Profile Picture</button>
</div>
{% endblock %}