app/information/__init__.py
from flask import Blueprint

bp = Blueprint('information', __name__, 'information')

from app.information import routes

app/information/routes.py
from app.information import bp
from flask import (
    render_template,
    send_from_directory,
    current_app,
    request,
    redirect,
    flash,
    url_for,
    g
)
from app.utils.db_utils import (
    _get_junkbite_node,
    _save_feedback,
    _save_support_ticket
)
from app.models import (
    SupportTicket,
    SupportTicketResponse,
    FAQEntry
)
from app import db
from app.email import (
    sendgrid_new_support_ticket
)

@bp.route('/info')
@bp.route('/information')
def info():
    return render_template('information/information.html')


@bp.route('/about')
def about():
    return render_template('information/about.html')


@bp.route('/help')
def help():
    return render_template('information/help.html')


@bp.route('/rules')
def rules():
    return render_template('information/rules.html')


@bp.route('/privacy-policy')
def privacy_policy():
    return render_template('information/privacy_policy.html')


@bp.route('/terms-of-service')
def terms_of_service():
    return render_template('information/terms_of_service.html')



@bp.route('/bitcoin.pdf')
def bitcoin_pdf():
    """
    Returns the sacred text
    """
    return send_from_directory(current_app.config['STATIC_FOLDER'], 'bitcoin.pdf')


@bp.route('/node-information')
def lightning_info():
    """
    Returns a page describing how to connect to junkbite lightning node
    """
    node = _get_junkbite_node()
    return render_template('information/lightning_node.html', node=node)


@bp.route("/frequently-asked-questions")
def faq():
    """
    Returns a document with answers to common questions on junkbite
    """
    faqs = FAQEntry.query.filter_by(visible=True).all()
    return render_template("information/faq.html", faqs=faqs)


@bp.route("/feedback", methods=["GET", "POST"])
def feedback():
    """
    A form for users to give feedback
    """
    if request.method == "POST":
        description = request.form.get("description")
        flash("Thanks")
        _save_feedback(description)
        return redirect(url_for('information.feedback'))
    return render_template('information/feedback.html')


@bp.route("/support", methods=["GET", "POST"])
def support():
    """
    A form for users to open support tickets
    """
    if request.method == "POST":
        description = request.form.get("description")
        ticket_code = _save_support_ticket(description)
        flash(f"Support ticket, opened. Ticket Code: {ticket_code}")
        sendgrid_new_support_ticket(description, ticket_code)
        return redirect(url_for('information.support_detail', ticket_code=ticket_code))
    if g.user:
        tickets = (
            SupportTicket.query.filter_by(user_id=g.user.id)
            .order_by(SupportTicket.created.desc())
        )
        return render_template('information/support.html', tickets=tickets)
    return render_template('information/support.html', tickets=None)


@bp.route("/support/<ticket_code>/detail", methods=["GET", "POST"])
def support_detail(ticket_code):
    """
    A form for users to open support tickets
    """
    ticket = SupportTicket.query.filter_by(ticket_code=ticket_code).first()
    if not g.user:
        flash("Unauthorized")
        return redirect(url_for("information.support"))
    if ticket.user_id != g.user.id and g.user.admin == False:
        flash("Unauthorized")
        return redirect(url_for("information.support"))
    if request.method == "POST":
        response = request.form.get("response")
        ticket_response = SupportTicketResponse(
            support_ticket_id=ticket.id,
            user_id=g.user.id,
            response_text=response,
        )
        db.session.add(ticket_response)
        db.session.commit()
        flash(f"Response added to ticket")
        return redirect(url_for('information.support_detail', ticket_code=ticket.ticket_code))
    return render_template(
        'information/support_detail.html',
        ticket=ticket
    )

app/templates/information/about.html
{% extends 'base.html' %}
{% block content %}
  <div id=about>
    <h1> About </h1>
    <p>
      <strong>junkbite</strong> is for sharing images, gifs, and videos and using the lightning network.
      Bitcoin is the future of money and lightning is the future of payments and its happening now.
      This website is lightning enabled so buy bitcoin, download a lightning wallet and start using it.
      Please read the <a href="{{ url_for('information.rules') }}"><strong>rules</strong></a>
      before posting.
    </p>
  </div>
{% endblock %}

app/templates/information/faq.html
{% extends 'base.html' %}

{% block content %}
<div id="faq">
    <h3 class="text-muted">Frequently Asked Questions</h3>
    <ul class="list-group list-group-flush border rounded">
        {% for f in faqs %}
        <li class="list-group-item mb-2">
            <h6 class="font-weight-bold">{{ f.question }}</h6>
            {{ f.answer | safe }}
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

app/templates/information/feedback.html
{% extends 'base.html' %}
{% block content %}
<div id="information">
    <h3 class="text-muted">Feedback</h3>
    <p class="lead">Help improve junkbite by giving feedback here</p>
    <form method="post" action="{{ url_for('information.feedback') }}">
        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" name="description" id="description" autocomplete=off>{{ request.form['description'] }}</textarea>
        </div>
        <input class="btn btn-primary" role="button" type="submit" value="Submit">
    </form>
</div>
{% endblock %}

app/templates/information/help.html
{% extends 'base.html' %}
{% block content %}
  <div id=help>
    <h3>Junkbite Functionality</h3>
    <h4>Overview of all functions available to a user.</h4>
    <strong>Lightning</strong><br>
    <p>
    Click the lightning bolt under a post, enter an amount (in satoshis) and click boost. A lightning network invoice will appear.
    Pay this using a lightning enabled wallet tip a user on a post. Tipping your own post will boost the post but the satoshis
    will go to junkbite, consider this a tip to junkbite and it is much appreciated.
    </p>
    <strong>Create</strong><br>
    <p>
    Create a meme, share an image or video or just post some text
    </p>
    <strong>Explore</strong><br>
    <p>
    This page shows popular content

    Clicking on one of these tiles will bring you to that specific thread
    </p>
    <strong>Home</strong><br>
    <p>
    Content from people you follow will appear here. Click the card to see comments.
    </p>
  </div>
{% endblock %}

app/templates/information/information.html
{% extends 'base.html' %}
{% block content %}
<div id="information">
    <h3 class="text-muted">Information Links</h3>
    <div class="card p-3">
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><a href="{{ url_for('information.about') }}">About</a></li>
            <li class="list-group-item"><a href="{{ url_for('information.faq') }}">FAQs</a></li>
            <li class="list-group-item"><a href="{{ url_for('information.lightning_info') }}">Lightning Node</a></li>
            <li class="list-group-item"><a href="{{ url_for('information.help') }}">Help</a></li>
            <li class="list-group-item"><a href="{{ url_for('information.bitcoin_pdf') }}">Bitcoin White Paper</a></li>
            <li class="list-group-item"><a href="{{ url_for('information.rules') }}">Rules</a></li>
            <li class="list-group-item"><a href="{{ url_for('information.support') }}">Support</a></li>
            <li class="list-group-item"><a href="{{ url_for('information.feedback') }}">Feedback</a></li>
            <li class="list-group-item"><a href="{{ url_for('information.privacy_policy') }}">Privacy Policy</a></li>
            <li class="list-group-item"><a href="{{ url_for('information.terms_of_service') }}">Terms of Service</a></li>
        </ul>
    </div>
</div>
{% endblock %}

app/templates/information/lightning_node.html
{% extends 'base.html' %}

{% block header %}<h4 class="text-muted">Junkbite Lightning Node Information</h4>{% endblock %}


{% block content %}
<div id="lightning-information">
    <div class="card">
        <div class="card-body">
            <h6 class="card-subtitle mb-2">Alias:
                <span class="text-muted">
                    <a target="_blank" href="https://1ml.com/node/03d84216cc025e8c035645d52d59b4723b0b7f23df21e6caeed9c67f39c1266ae7">{{node.title}}</a> (1ml.com profile)
                </span>
            </h6>
            <h5 class="card-title">Node URI</h5>
            <input readonly type="text" class="form-control" id="lnNodePubkey" value="{{node.uri}}"><br>
            <button class="btn btn-primary" onclick="copyPubkey('lnNodePubkey')">Copy</button>
            <hr>
            <h5 class="card-title">How to connect with LND</h5>
            <p class="lead">Use `lncli` to open up a 2 million sat channel with Junkbite</p>
            <pre class="bg-light border rounded p-1">lncli connect {{node.uri}}<br>lncli openchannel {{node.pubkey}} 2000000</pre>
            <hr>
            <h5 class="card-title">How to connect with c-lightning</h5>
            <p class="lead">use `lightning-cli` to open up a 2 million sat channel with Junkbite</p>
            <pre class="bg-light border rounded p-1">lightning-cli connect {{node.uri}}<br>lightning-cli fundchannel --id={{node.pubkey}} --amount=2000000</pre>
        </div>
    </div>
</div>
{% endblock %}

app/templates/information/privacy_policy.html
{% extends 'base.html' %}

{% block content %}
<div id="faq">
    <h3 class="text-muted">Junkbite Privacy Policy</h3>
    <div class="card p-3">
        <p>This Privacy Policy describes how your personal information is collected, used, and shared when you visit or make a purchase from junkbite.com (the "Site").</p>
        <h4>PERSONAL INFORMATION WE COLLECT</h4>
        <p>
            When you visit the Site, we automatically collect certain information about your device, including information about your web browser, IP address, time zone, and some of the cookies that are installed on your device. Additionally, as you browse the Site, we collect information about the individual web pages you view, and information about how you interact with the Site. We refer to this automatically-collected information as "Device Information."
            We collect Device Information using the following technologies:
            <ul>
                <li>"Cookies" are data files that are placed on your device or computer and often include an anonymous unique identifier. For more information about cookies, and how to disable cookies, visit http://www.allaboutcookies.org.</li>
                <li>"Log files" track actions occurring on the Site, and collect data including your IP address, and date/time stamps.</li>
            </ul>
            Additionally when you make a purchase or attempt to make a purchase through the Site, we collect certain information from you like email address.  We refer to this information as "Order Information."
            When we talk about "Personal Information" in this Privacy Policy, we are talking both about Device Information and Order Information.
        </p>
        <h4>HOW DO WE USE YOUR PERSONAL INFORMATION?</h4>
        <p>
            We use the Order Information that we collect generally to fulfill any orders placed through the Site (including processing your payment information, arranging for shipping, and providing you with invoices and/or order confirmations).  Additionally, we use this Order Information to:
            Communicate with you;
            Screen our orders for potential risk or fraud; and
            When in line with the preferences you have shared with us, provide you with information or advertising relating to our products or services.
            We use the Device Information that we collect to help us screen for potential risk and fraud (in particular, your IP address), and more generally to improve and optimize our Site
        </p>
        <h4>SHARING YOUR PERSONAL INFORMATION</h4>
        <p>
            We may share your Personal Information to comply with applicable laws and regulations, to respond to a subpoena, search warrant or other lawful request for information we receive, or to otherwise protect our rights.
        </p>
        <h4>BEHAVIOURAL ADVERTISING</h4>
        <p>There are no advertisements currently on junkbite and theres no plans to add them, we don't collect sufficient data for this to be successful anyways.</p>
        <h4>DO NOT TRACK</h4>
        <p>Please note that we do not alter our Site’s data collection and use practices when we see a Do Not Track signal from your browser.</p>
        <h4>YOUR RIGHTS</h4>
        <p>If you are a European resident, you have the right to access personal information we hold about you and to ask that your personal information be corrected, updated, or deleted. If you would like to exercise this right, please contact us through the contact information below.
            Additionally, if you are a European resident we note that we are processing your information in order to fulfill contracts we might have with you (for example if you make an order through the Site), or otherwise to pursue our legitimate business interests listed above.  Additionally, please note that your information will be transferred outside of Europe, including to Canada and the United States.
        </p>
        <h4>DATA RETENTION</h4>
        <p>When you place an order through the Site, we will maintain your Order Information for our records unless and until you ask us to delete this information.</p>
        <h4>MINORS</h4>
        <p>The Site is not intended for individuals under the age of 18.</p>
        <h4>CHANGES</h4>
        <p>We may update this privacy policy from time to time in order to reflect, for example, changes to our practices or for other operational, legal or regulatory reasons.</p>
        <h4>CONTACT US</h4>
        <p>For more information about our privacy practices, if you have questions, or if you would like to make a complaint, please contact us by e-mail at psqnt@junkbite.com</p>
    </div>
</div>
{% endblock %}

app/templates/information/rules.html
{% extends 'base.html' %}
{% block content %}
    <div id="rules">
        <h3 class="text-muted">Rules</h3>
        <hr>
        <strong>No Hacking</strong>
        <p>Do not hack junkbite.</p>
        <strong>Prohibited Content</strong><br>
        Do not post any content that is:<br><br>
        <ul>
            <li>illegal</li>
            <li>involuntary pornography</li>
            <li>sexual or suggestive content involving minors</li>
            <li>incites violence</li>
            <li>threatening or harassment</li>
            <li>personal and confidential information</li>
            <li>spam</li>
        </ul>
    </div>
{% endblock %}

app/templates/information/support.html
{% extends 'base.html' %}
{% block content %}
<div id="information">
    <h3 class="text-muted">Support</h3>
    <p class="lead">Open a ticket here with a description of your issue so it can be resolved</p>
    <form method="post" action="{{ url_for('information.support') }}">
        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" name="description" id="description" autocomplete=off>{{ request.form['description'] }}</textarea>
        </div>
        <input class="btn btn-primary" role="button" type="submit" value="Submit">
    </form>
    {% if tickets %}
        <hr>
        <h4 class="text-muted">Your Support Tickets</h4>
        {% for ticket in tickets %}
        <div class="mb-2">
            <a href="{{ url_for('information.support_detail', ticket_code=ticket.ticket_code) }}">{{ticket.ticket_code}}</a><span>  <small class="text-muted">{{ticket.created|strftime }}</small></span>
        </div>
        <hr>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

app/templates/information/support_detail.html
{% extends 'base.html' %}
{% block content %}
<div id="supportDetail">
    <h3 class="text-muted">Support Ticket: {{ ticket.ticket_code}} </h3>
    {% if ticket.ticket_status == 'closed' %}
    <span class="text-warning">{{ticket.ticket_status}}</span>
    {% else %}
    <span class="text-info">{{ticket.ticket_status}}</span>
    {% endif %}
    <p class="lead">{{ ticket.description }}</p>
    <span class="text-info">{{ ticket.user.username }}</span>
    {% if ticket.ticket_status == "opened" %}
    <hr>
    <form method="post" action="{{ url_for('information.support_detail', ticket_code=ticket.ticket_code) }}">
        <div class="form-group">
            <label for="response">Response</label>
            <textarea class="form-control" name="response" id="response" autocomplete=off></textarea>
        </div>
        <input class="btn btn-primary" role="button" type="submit" value="Submit">
    </form>
    {% endif %}
    <hr>
    {% for response in ticket.responses %}
    <div class="mb-2">
        <span class="text-info">{{ response.user.username }}: </span>
        <span>{{ response.response_text }}</span>
        <hr>
    </div>
    {% endfor %}
</div>
{% endblock %}