app/bounty/__init__.py
from flask import Blueprint

bp = Blueprint('bounty', __name__)

from app.bounty import routes

app/bounty/routes.py
from app.auth.utils import login_required
from app.utils.meta_utils import (
    _datetime_to_humantime,
    _sqliterow_to_dict,
)
from flask import (
    current_app,
    g,
    flash,
    request,
    redirect,
    render_template,
    url_for,
)
from werkzeug.exceptions import abort
from app.bounty import bp
from app.email import sendgrid_new_bounty_response
from app.utils.db_utils import (
    _delete_bounty_response_upvote,
    _get_bounty_user_id,
    _get_bounty_detail,
    _get_bounty,
    _get_all_bounties,
    _get_bounty_id_by_response_code,
    _get_closed_bounties,
    _get_open_bounties,
    _get_user_bounties,
    _get_current_user_id,
    _get_bounty_response_user_id,
    _get_bounty_user_id,
    _get_bounties_user_responded_to,
    _get_bounty_winner_info,
    _get_bounty_response_upvote,
    _get_bounty_from_bounty_code,
    _get_max_withdrawal_amount,
    _has_invoice_been_paid,
    _save_bounty_response_upvote,
    _save_bounty,
    _save_bounty_response,
    _set_bounty_winner_and_close,
    _update_user_balance,
    _save_bounty_payout,
    _save_bounty_creation_payment,
    _save_payment,
    _save_notification
)
from lndgrpc import LNDClient


OPEN_BOUNTIES = 'bounty.open_bounties'
BOUNTIES_HTML = 'bounty/bounties.html'
BOUNTY_DETAIL_VIEW = 'bounty.view_bounty'
INJECTABLE_BOUNTIES = 'bounty/injectable_bounties.html'


@bp.route('/award-bounty/<bounty_code>', methods=("POST",))
@login_required
def award_bounty(bounty_code):
    response_winner_id = request.form.get('bountyResponseWinner')
    # set bounty winner, pay winning user and close
    bounty = _get_bounty(bounty_code)
    if bounty.status != "open":
        flash('Bounty already closed')
        return redirect(url_for(BOUNTY_DETAIL_VIEW, bounty_code=bounty.bounty_code))
    response_user_id = _get_bounty_response_user_id(response_winner_id)
    bounty_id = bounty.id
    if not g.user or g.user.id != bounty.user_id:
        flash("This is not your bounty to award")
        return redirect(url_for(BOUNTY_DETAIL_VIEW, bounty_code=bounty_code))
    if bounty.user_id == response_user_id:
        flash("You cannot award yourself the bounty")
        return redirect(url_for(BOUNTY_DETAIL_VIEW, bounty_code=bounty_code))
    _set_bounty_winner_and_close(bounty_id, response_winner_id)
    amount, ln_invoice, user_id = _get_bounty_winner_info(bounty_id)
    bounty_creator_user_id = _get_bounty_user_id(bounty_id)
    # create payment for winning bounty and update user balance
    was_balance_updated = _save_bounty_payout(
        bounty_code=bounty_code,
        amount=amount,
        ln_invoice=ln_invoice,
        bounty_id=bounty_id,
        junkbite_app="bounty",
        payment_type="bounty winner",
        receiving_user_id=user_id,
        sending_user_id=bounty_creator_user_id
    )
    if not was_balance_updated:
        flash('Award already claimed')
        return redirect(url_for(BOUNTY_DETAIL_VIEW, bounty_code=bounty_code))
    content = f"{g.user.username} has awarded you a bounty"
    _save_notification(
        response_user_id, g.user.id, content, bounty_id=bounty_id
    )
    flash('Bounty Awarded and Closed')
    return redirect(url_for(BOUNTY_DETAIL_VIEW, bounty_code=bounty_code))


@bp.route('/all-bounties')
def all_bounties():
    title = 'All Bounties'
    bounties = _get_all_bounties(limit=20, offset=0)
    return render_template(
        BOUNTIES_HTML,
        title=title,
        bounties=bounties
    )


@bp.route('/open-bounties')
def open_bounties():
    title = 'Open Bounties'
    bounties = _get_open_bounties(limit=20, offset=0)
    return render_template(
        BOUNTIES_HTML,
        title=title,
        bounties=bounties
    )


@bp.route('/closed-bounties')
def closed_bounties():
    title = 'Closed Bounties'
    bounties = _get_closed_bounties(limit=20, offset=0)
    return render_template(
        BOUNTIES_HTML,
        title=title,
        bounties=bounties
    )


@bp.route('/create-bounty', methods=('GET', 'POST'))
@login_required
def create_bounty():
    """
    View to create a new bounty
    """
    title = 'Create Bounty'
    maximum_withdrawal_amount = _get_max_withdrawal_amount()
    if request.method == 'POST':
        title = request.form.get('title')
        body = request.form.get('editorText')
        invoice = request.form.get("invoiceSubmit")
        if not title:
            flash('Title is required.')
            return redirect(url_for('bounty.create_bounty'))
        if body == "<p><br></p>":
            flash('Body is required.')
            return redirect(url_for('bounty.create_bounty'))
        # using wysiwyg editor now so no markdown processing
        processed_body = body
        # save bounty - pull info from ln invoice
        lnd = LNDClient(
            ip_address=current_app.config["LND_RPC_IP"],
            macaroon_filepath=current_app.config['LND_MACAROON'],
            cert_filepath=current_app.config['LND_TLS_CERT'],
            admin=True
        )
        info = lnd.decode_payment_request(invoice)
        amount = info.num_satoshis
        if amount > maximum_withdrawal_amount:
            flash(f'Max bounty is {maximum_withdrawal_amount} sats')
            return redirect(url_for('bounty.create_bounty'))
        upload = None
        filename = None
        user_id = _get_current_user_id()
        bounty = _save_bounty(
            title,
            body,
            processed_body,
            user_id, 
            upload,
            filename,
            amount,
            invoice
        )
        _save_bounty_creation_payment(
            amount=amount,
            ln_invoice=invoice,
            bounty_id=bounty.id,
            junkbite_app="bounty",
            payment_type="bounty creation",
        )
        return redirect(url_for(BOUNTY_DETAIL_VIEW, bounty_code=bounty.bounty_code))
    return render_template(
        'bounty/create_bounty.html',
        title=title,
        max_zap=maximum_withdrawal_amount
    )


@bp.route('/u/<username>/user-bounties', methods=("GET",))
@login_required
def user_bounties(username):
    """
    View a user's bounties
    """
    title = "Bounties you created"
    bounties = _get_user_bounties(username)
    return render_template(
        BOUNTIES_HTML,
        title=title,
        bounties=bounties
    )


@bp.route('/get-create-bounty-invoice', methods=["POST"])
@login_required
def get_create_bounty_invoice():
    """
    Get a bounty invoice to finalize the creation of the bounty
    """
    amount = request.form.get("amount")
    if amount is None:
        return {'message': 'failed'}
    amount = int(amount)
    maximum_withdrawal_amount = _get_max_withdrawal_amount()
    if amount > maximum_withdrawal_amount:
        return {'message': f'Max zap is {maximum_withdrawal_amount} sats'}
    lnd = LNDClient(
        ip_address=current_app.config["LND_RPC_IP"],
        macaroon_filepath=current_app.config['LND_MACAROON'],
        cert_filepath=current_app.config['LND_TLS_CERT'],
        admin=True
    )
    response = lnd.add_invoice(amount)
    ln_invoice = response.payment_request
    _save_payment(
        amount=amount,
        ln_invoice=ln_invoice,
        junkbite_app="bounty",
        payment_type="bounty creation"
    )
    return {'message': ln_invoice}


@bp.route('/get-bounty-invoice', methods=("POST",))
def get_bounty_invoice():
    """
    Get a payment invoice to boost a bounty
    """
    bounty_id = request.form.get("bountyId")
    payment_amount = int(request.form.get("amount"))
    maximum_withdrawal_amount = _get_max_withdrawal_amount()
    if payment_amount > maximum_withdrawal_amount:
        return {'message': f'Max zap is {maximum_withdrawal_amount} sats'}
    lnd = LNDClient(
        ip_address=current_app.config["LND_RPC_IP"],
        macaroon_filepath=current_app.config['LND_MACAROON'],
        cert_filepath=current_app.config['LND_TLS_CERT'],
        admin=True
    )
    response = lnd.add_invoice(payment_amount)
    ln_invoice = response.payment_request
    if bounty_id:
        _save_payment(
            amount=payment_amount,
            ln_invoice=ln_invoice,
            bounty_id=bounty_id,
            junkbite_app="bounty",
            payment_type="sat boost on bounty"
        )
    else:
        return {'message': 'failed to determine bounty'}
    return {'message': ln_invoice}


@bp.route('/get-bounty-response-invoice', methods=("POST",))
def get_bounty_response_invoice():
    """
    Get a bounty invoice
    """
    response_id = request.form.get("responseId")
    payment_amount = int(request.form.get("amount"))
    maximum_withdrawal_amount = _get_max_withdrawal_amount()
    if payment_amount > maximum_withdrawal_amount:
        return {'message': f'Max zap is {maximum_withdrawal_amount} sats'}
    lnd = LNDClient(
        ip_address=current_app.config["LND_RPC_IP"],
        macaroon_filepath=current_app.config['LND_MACAROON'],
        cert_filepath=current_app.config['LND_TLS_CERT'],
        admin=True
    )
    response = lnd.add_invoice(payment_amount)
    ln_invoice = response.payment_request
    if response_id:
        _save_payment(
            amount=payment_amount,
            ln_invoice=ln_invoice,
            response_id=response_id,
            junkbite_app="bounty",
            payment_type="sat boost on bounty response"
        )
    else:
        return {'message': 'failed to determine bounty response'}
    return {'message': ln_invoice}


@bp.route('/response-upvote', methods=("POST",))
def response_upvote():
    '''
    upvotes a bounty response
    '''
    response_id = request.form.get('responseId')
    if not g.user:
        return {'message': 'login to upvote'}
    # check if response_id has already been upvoted
    upvote = _get_bounty_response_upvote(response_id, g.user.id)
    if upvote:
        _delete_bounty_response_upvote(upvote)
        return {'message': 'deleted'}
    _save_bounty_response_upvote(response_id, g.user.id)

app/templates/bounty/_bounty_bottom_buttons.html
<span class="pr-2" data-toggle="modal" data-target="#shareModal">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-upload" viewBox="0 0 16 16">
        <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
        <path d="M7.646 1.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 2.707V11.5a.5.5 0 0 1-1 0V2.707L5.354 4.854a.5.5 0 1 1-.708-.708l3-3z"/>
    </svg>
</span>
{% if bounty.status == 'open' %}
<span class="pr-2" onclick="toggleIncreaseBountyForm({{ bounty.id }})">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-lightning-charge" viewBox="0 0 16 16">
        <path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09zM4.157 8.5H7a.5.5 0 0 1 .478.647L6.11 13.59l5.732-6.09H9a.5.5 0 0 1-.478-.647L9.89 2.41 4.157 8.5z"/>
    </svg>
</span>
{% endif %}
<small class="text-warning" id="satsAmount{{bounty.id}}">{{ bounty.total_sats }}</small>

app/templates/bounty/_bounty_header.html
<nav class="nav nav-tabs" style="white-space:nowrap;overflow-x:auto;">
    <ul class="pl-0">
        {% if g.user %}
            {% if request.endpoint == 'bounty.create_bounty'%}
                <a class="active pl-2 pr-2" href="{{ url_for('bounty.create_bounty') }}">Create</a>
            {% else %}
                <a class="pl-2 pr-2" href="{{ url_for('bounty.create_bounty') }}">Create</a>
            {% endif %}
            {% if request.endpoint == 'bounty.user_bounties'%}
                <a class="active pl-2 pr-2" href="{{ url_for('bounty.user_bounties', username=g.user.username) }}">Your Bounties</a>
            {% else %}
                <a class="pl-2 pr-2" href="{{ url_for('bounty.user_bounties', username=g.user.username) }}">Your Bounties</a>
            {% endif %}
            {% if request.endpoint == 'bounty.user_responded_bounties'%}
                <a class="active pl-2 pr-2" href="{{ url_for('bounty.user_responded_bounties', username=g.user.username) }}">Your Responses</a>
            {% else %}
                <a class="pl-2 pr-2" href="{{ url_for('bounty.user_responded_bounties', username=g.user.username) }}">Your Responses</a>
            {% endif %}
        {% endif %}
        {% if request.endpoint == 'bounty.all_bounties' %}
        <a class="active pl-2 pr-2" href="{{ url_for('bounty.all_bounties') }}">All</a>
        <a class="pl-2 pr-2" href="{{ url_for('bounty.open_bounties') }}">Open</a>
        <a class="pl-2 pr-2" href="{{ url_for('bounty.closed_bounties') }}">Closed</a>
        {% endif %}
        {% if request.endpoint == 'bounty.open_bounties' %}
        <a class="pl-2 pr-2" href="{{ url_for('bounty.all_bounties') }}">All</a>
        <a class="active pl-2 pr-2" href="{{ url_for('bounty.open_bounties') }}">Open</a>
        <a class="pl-2 pr-2" href="{{ url_for('bounty.closed_bounties') }}">Closed</a>
        {% endif %}
        {% if request.endpoint == 'bounty.closed_bounties' %}
        <a class="pl-2 pr-2" href="{{ url_for('bounty.all_bounties') }}">All</a>
        <a class="pl-2 pr-2" href="{{ url_for('bounty.open_bounties') }}">Open</a>
        <a class="active pl-2 pr-2" href="{{ url_for('bounty.closed_bounties') }}">Closed</a>
        {% endif %}
        {% if request.endpoint == 'bounty.create_bounty' %}
        <a class="pl-2 pr-2" href="{{ url_for('bounty.all_bounties') }}">All</a>
        <a class="pl-2 pr-2" href="{{ url_for('bounty.open_bounties') }}">Open</a>
        <a class="pl-2 pr-2" href="{{ url_for('bounty.closed_bounties') }}">Closed</a>
        {% endif %}
        {% if request.endpoint == 'bounty.user_bounties'%}
        <a class="pl-2 pr-2" href="{{ url_for('bounty.all_bounties') }}">All</a>
        <a class="pl-2 pr-2" href="{{ url_for('bounty.open_bounties') }}">Open</a>
        <a class="pl-2 pr-2" href="{{ url_for('bounty.closed_bounties') }}">Closed</a>
        {% endif %}
        {% if request.endpoint == 'bounty.user_responded_bounties'%}
        <a class="pl-2 pr-2" href="{{ url_for('bounty.all_bounties') }}">All</a>
        <a class="pl-2 pr-2" href="{{ url_for('bounty.open_bounties') }}">Open</a>
        <a class="pl-2 pr-2" href="{{ url_for('bounty.closed_bounties') }}">Closed</a>
        {% endif %}
    </ul>
</nav>
<br>
{% block title %}
    <h4 class="header-title">{{ title }}</h4>
{% endblock %}
<hr>

app/templates/bounty/_bounty_lightning_boost.html
<div id="zapBountyError" style="display: none">
    <small class="text-danger">Invalid Amount - Max {{ max_zap if max_zap else 1000 }} sats</small>
</div>
<div class="pt-2" id="bountyZapForm{{ bounty.id }}" style="display: none;">
    <small class="pl-1">Sats</small>
    <div class="row">
        <form class="col-3">
            <input
                type="number"
                class="form-control mr-1"
                id="increaseBounty{{ bounty.id}}"
                min="1"
                max="{{ max_zap if max_zap else 1000 }}"
                step="1"
                value="200"
            >
        </form>
        <button class="col-3 btn btn-warning" onclick="getBountyInvoice('{{bounty.id}}', '{{ max_zap if max_zap else 1000 }}')">Increase</button>
    </div>
</div>

app/templates/bounty/_bounty_list_item.html
<div class="card">
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ url_for('bounty.view_bounty', bounty_code=bounty.bounty_code) }}">{{ bounty.title }}</a>
        </h5>
        <hr>
        {% if bounty.status == 'closed' %}
        <h3><span class="badge badge-info">CLOSED</span></h3>
        <small>Bounty: <span class="text-warning">{{ bounty.total_sats }} sats</span></small>
        {% else %}
        <h3><span class="badge badge-warning">{{ bounty.total_sats }} sats</span></h3>
        {% endif %}
        <small class="form-text text-muted">{{ bounty.created|strftime }}</small>
        <small class="form-text text-warning">{{ bounty.status }}</small>
        {% if bounty.response_count == 1 %}
        <small class="text-muted">{{ bounty.response_count }} response</small>
        {% else %}
        <small class="text-muted">{{ bounty.response_count }} responses</small>
        {% endif %}
    </div>
</div>

app/templates/bounty/_bounty_modal_invoice.html
<div class="modal fade" id="invoiceBounty{{bounty.id}}" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="invoiceLabel">Payment Request</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="qrcode-display" id="qrcodeBounty{{bounty.id}}"></div>
                <div id="lightningInvoiceText{{bounty.id}}">
                    <hr>
                    <div class="form-group">
                        <input readonly type="text" class="form-control" id="invoiceBountyText{{bounty.id}}"><br>
                        <button type="button" class="btn btn-primary" onclick="copyBountyInvoice({{bounty.id}})">Copy Invoice</button>
                    </div>
                </div>
                <div id="qrcodeBountyCompleted{{bounty.id}}" style="display:none;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-lightning-fill" viewBox="0 0 32 32">
                        <path d="M5.52.359A.5.5 0 0 1 6 0h4a.5.5 0 0 1 .474.658L8.694 6H12.5a.5.5 0 0 1 .395.807l-7 9a.5.5 0 0 1-.873-.454L6.823 9.5H3.5a.5.5 0 0 1-.48-.641l2.5-8.5z"/>
                    </svg>
                    <h3>Payment Complete!</h3>
                </div>
            </div>
            <div class="modal-footer">
                <span class="text-muted">Scan this with a lightning wallet to complete</span>
                <a href="{{ url_for('information.help') }}">help</a>
            </div>
        </div>
    </div>
</div>

app/templates/bounty/_bounty_response_lightning_boost.html
<div id="zapBountyResponseError{{response.id}}" style="display: none">
    <small class="text-danger">Invalid Amount - Max {{ max_zap if max_zap else 1000 }} sats</small>
</div>
<div id="thread-boost-form{{ response.id }}" style="display: none;">
    <small class="pl-1">Sats</small>
    <div class="row">
        <form class="col-3">
            <input  
                type="number"
                class="form-control mr-1"
                id="input-sats{{ response.id}}"
                min="1"
                max="{{ max_zap if max_zap else 1000 }}"
                step="1"
                value="200"
            >
        </form>
        <button class="col-3 btn btn-warning" onclick="getBountyResponseInvoice('{{response.id}}', '{{ max_zap if max_zap else 1000 }}')">Zap</button>
    </div>
</div>

app/templates/bounty/_bounty_response_modal_invoice.html
<div class="modal fade" id="invoice{{response.id}}" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="invoiceLabel">Payment Request</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="qrcode-display" id="qrcode{{response.id}}"></div>
                <div id="lightningInvoiceText{{response.id}}">
                    <hr>
                    <div class="form-group">
                        <input readonly type="text" class="form-control" id="invoiceText{{response.id}}"><br>
                        <button type="button" class="btn btn-primary" onclick="copyInvoice({{response.id}})">Copy Invoice</button>
                    </div>
                </div>
                <div id="qrcode{{response.id}}-completed" style="display:none;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-lightning-fill" viewBox="0 0 32 32">
                        <path d="M5.52.359A.5.5 0 0 1 6 0h4a.5.5 0 0 1 .474.658L8.694 6H12.5a.5.5 0 0 1 .395.807l-7 9a.5.5 0 0 1-.873-.454L6.823 9.5H3.5a.5.5 0 0 1-.48-.641l2.5-8.5z"/>
                    </svg>
                    <h3>Payment Complete!</h3>
                </div>
            </div>
            <div class="modal-footer">
                <span class="text-muted">Scan this with a lightning wallet to complete</span>
                <a href="{{ url_for('information.help') }}">help</a>
            </div>
        </div>
    </div>
</div>

app/templates/bounty/bounty_detail.html
{% extends 'base.html' %}
{% block content %}
<div id='bounty{{ bounty.id }}' class="card col-lg-8 offset-lg-2" style="overflow: hidden">
    <div id="bounty-container-{{ bounty.id }}" class="card-body">
        <nav class="nav navbar-expand pb-2 pl-2">
            <div class="container-fluid pt-2">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{{ url_for('bombadillo.view_user', username=bounty.user.username) }}">
                            {% if bounty.user.unique_filename %}
                            <img id="userProfileImg{{bounty.user.username}}" style="height: 32px; width: 32px;"
                                src="{{ url_for('static', filename='images/{}'.format(bounty.user.unique_filename) ) }}"
                                class="rounded-circle" onerror="loadDefaultProfileImg('userProfileImg{{bounty.user.username}}')" alt="">
                            {% else %}
                            <img style="height: 32px; width: 32px;"
                                src="{{ url_for('static', filename='images/default-profile.png') }}"
                                class="rounded-circle" alt="">
                            {% endif %}
                        </a>
                    </li>
                    <li class="nav-item pl-2 pt-1">
                        <span class="font-weight-normal">{{ bounty.user.username }}</span>
                    </li>
                </ul>
            </div>
        </nav>
        <hr>
        <div class="single-bounty-content-wrapper p-3" id="bounty{{ bounty.id }}">
            <h3>
                <small class="text-muted">{{ bounty.title }}</small>
            </h3>
            {% if bounty.status == 'closed' %}
            <h3><span class="badge badge-info">CLOSED</span></h3>
            <small>Bounty: <span class="text-warning">{{ bounty.initial_sats }} sats</span></small>
            {% else %}
            <h3><span class="badge badge-warning">{{ bounty.initial_sats }} sats</span></h3>
            {% endif %}
            <small class="form-text text-muted">{{ bounty.created|strftime }}</small>
            <hr>
            <div class="bountyInformationContainer">
                {{ bounty.processed_body | safe }}
            </div>
        </div>
        <div>
            {% include 'bounty/_bounty_bottom_buttons.html' %}
            {% include 'bounty/_bounty_lightning_boost.html' %}
            {% include 'bounty/_bounty_share_modal.html' %}
            {% include 'bounty/_bounty_modal_invoice.html' %}
        </div>
        <div>
            {% if g.user and bounty.user_id != g.user.id and bounty.status == 'open' %}
            <form method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="response">Bounty Response</label>
                    <textarea class="form-control" name="response" id="responseText" autocomplete=off aria-describedby="responseHelp">{{ request.form['body'] }}</textarea>
                    <small id="responseHelp" class="form-text text-muted">Responding to this allows you to compete to win the bounty</small>
                </div>
                <input class="btn btn-primary" role="button" type="submit" value="Submit" />
            </form>
            {% endif %}
            <form id="bountyResponseWinnerForm" action="{{ url_for('bounty.award_bounty', bounty_code=bounty.bounty_code) }}" style="display: none;" method="post">
                <div class="form-group">
                    <input type="text" name="bountyResponseWinner" id="bountyResponseWinner">
                </div>
            </form>
            <hr>
            {% for response in responses %}
                {% if response.bounty_winner %}
                <div id="response-{{ response.id }}" style="padding: 1em; border-radius: 1em; border: 2px solid orange">
                    <h6 class="text-warning">Bounty Winner</h6>
                {% else %}
                <div id="response-{{ response.id }}">
                {% endif %}
                    <div id="response-header">
                        <a href="{{ url_for('bombadillo.view_user', username=response.user.username) }}"><strong>{{ response.username }}</strong></a>
                        <small class="form-text text-muted">{{ response.created|strftime }}</small>
                    </div>
                    <div id="responseContainer{{ response.id }}">
                        <div class="row" id="response-container-{{ response.id }}">
                            <div class="col bountyResponseText" id="response{{ response.id }}">
                                {{ response.processed_body | safe }}
                            </div>
                        </div>
                    </div>
                    <br>
                    {% include 'bounty/_bounty_response_button_actions.html' %}
                    {% include 'bounty/_bounty_response_lightning_boost.html' %}
                    {% include 'bounty/_bounty_response_modal_invoice.html' %}
                    {% if bounty.status == 'open' and bounty.user_id == g.user.id %}
                    <div>
                        <button class="mt-2 btn btn-primary" onclick="awardBountyPrompt('bountyAward{{response.id}}')">Award</button>
                        <div class="pt-2" id="bountyAward{{response.id}}" style="display: none">
                            <h4>Award this bounty and close?</h4>
                            <button class="btn btn-success" onclick="awardBountySubmit('{{response.id}}')">Yes</button>
                            <button class="btn btn-warning" onclick="awardBountyPrompt('bountyAward{{response.id}}')">Hide</button>
                        </div>
                    </div>
                    {% endif %}
                </div>
                <hr>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}