app/bombadillo/__init__.py
from flask import Blueprint

bp = Blueprint('bombadillo', __name__)

from app.bombadillo import routes, cli

app/bombadillo/routes.py
import bleach
from datetime import datetime
from flask import (
    flash,
    g,
    redirect,
    render_template,
    request,
    session,
    url_for,
    current_app,
)
from app import db
from app.auth.utils import login_required
from app.utils.tenor_utils import search_tenor_gifs
from app.bombadillo import bp
from app.utils.meta_utils import (
    _process_request_file,
    _default_limit,
    _default_offset
)
from app.utils.db_utils import (
    _delete_bookmark,
    _delete_comment_like,
    _delete_comment,
    _delete_follow,
    _delete_post,
    _delete_post_like,
    _get_bookmark,
    _get_comment,
    _get_follow,
    _get_images,
    _get_post_author,
    _get_post_user_id,
    _get_post_likes,
    _get_post_zaps,
    _get_junkbite_user_id,
    _get_user,
    _get_user_posts,
    _get_user_drafts,
    _get_followed_users,
    _get_advertisement_post_ids,
    _get_advertisement_posts,
    _get_anon_user_id,
    _get_anon_user,
    _get_max_withdrawal_amount,
    _get_user_by_username,
    _get_current_user_id,
    _get_comment_like,
    _get_user_followers,
    _get_user_following,
    _get_comment_by_id,
    _get_bookmarked_posts,
    _get_zapped_posts,
    _get_liked_posts,
    _get_explore_posts,
    _get_random_post,
    _get_notifications,
    _get_post_like,
    _get_post_comments,
    _get_comment_comments,
    _get_post_id_from_post_code,
    _get_comment_id_from_comment_code,
    _get_post,
    _get_settings,
    _get_threads,
    _get_users,
    _get_sent_user_payment_history,
    _get_received_user_payment_history,
    _get_lightning_app_price,
    _get_user_by_id,
    _get_user_balance,
    _get_user_profile_picture,
    _has_invoice_been_paid,
    _get_withdrawals,
    _mark_notification_as_read,
    _mark_unread_notifications_as_read,
    _save_bookmark,
    _save_comment_like,
    _save_comment,
    _save_follow,
    _save_post,
    _save_article,
    _save_notification,
    _save_node_uri,
    _save_post_like,
    _save_payment,
    _save_user_profile,
    _save_withdrawal,
    _search_users,
    _search_posts,
    _search_bounties,
    _update_user_balance,
    _update_user_password
)
from app.email import send_email_new_reported_post
from app.email import (
    sendgrid_password_updated,
    sendgrid_new_like_on_post,
    sendgrid_new_comment_on_post,
    sendgrid_new_comment_on_comment,
    sendgrid_new_follower,
    sendgrid_notify_admin_new_post,
    sendgrid_notify_admin_new_withdrawal
)
from lndgrpc import LNDClient
from app.models import ReportedContent, Comment  # TODO move this to db_utils

BOMBADILLO_POST = 'bombadillo.post'


@bp.before_request
def update_last_active():
    if g.user:
        g.user.last_active = datetime.utcnow()
        db.session.add(g.user)
        db.session.commit()


@bp.route('/api')
def api():
    return redirect(url_for('api.docs'))


@bp.route('/save-draft', methods=("POST",))
def save_draft():
    """
    Saves a post as a draft
    """
    title = request.form.get('title')
    title = bleach.clean(title)
    success, upload, unique_filename = _process_request_file(request)
    if not success:
        flash(current_app.config['FILE_TYPE_UNSUPPORTED'])
        return redirect(url_for('bombadillo.create'))
    if (title.isspace() or title.strip() == "") and unique_filename is None:
        flash("Not saving an empty draft")
        return redirect(url_for('bombadillo.create'))
    body = ""
    processed_body = ""
    user_id = _get_current_user_id()
    post = _save_post(
        title, body, processed_body, user_id, upload, unique_filename, draft=True
    )
    return redirect(url_for('bombadillo.edit_draft', post_code=post.post_code))


@bp.route('/edit-draft/<post_code>', methods=("GET", "POST"))
def edit_draft(post_code):
    """
    Edit a draft and publish
    """
    post = _get_post(post_code)
    if request.method == "POST":
        title = request.form.get('title')
        title = bleach.clean(title)
        success, upload, unique_filename = _process_request_file(request)
        if not success:
            flash(current_app.config['FILE_TYPE_UNSUPPORTED'])
            return redirect(url_for('bombadillo.create'))
        if (title.isspace() or title.strip() == "") and unique_filename is None:
            flash("Not saving an empty draft")
            return redirect(url_for('bombadillo.create'))
        body = ""
        processed_body = ""
        post.title = title
        post.body = body
        post.processed_body = processed_body
        post.upload = upload
        post.unique_filename = unique_filename
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('bombadillo.edit_draft', post_code=post.post_code))
    user = post.user
    return render_template("bombadillo/edit_draft.html", post=post, user=user)


@bp.route('/create-from-draft/<post_code>', methods=("POST",))
def create_from_draft(post_code):
    """
    Creates a thread but from a pre-existing draft post -- from edit page
    """
    post = _get_post(post_code)
    if not g.user or g.user.id != post.user.id:
        flash("Unauthorized")
        return redirect(url_for("bombadillo.threads"))
    title = request.form.get('title')
    title = bleach.clean(title)
    success, upload, unique_filename = _process_request_file(request)
    if not success:
        flash(current_app.config['FILE_TYPE_UNSUPPORTED'])
        return redirect(url_for('bombadillo.create'))
    if (title.isspace() or title.strip() == "") and unique_filename is None:
        flash("Your post cannot be empty")
        return redirect(url_for('bombadillo.create'))
    post.title = title
    post.draft = False
    if unique_filename:
        post.upload = upload
        post.unique_filename = unique_filename
    db.session.add(post)
    db.session.commit()
    return redirect(url_for(BOMBADILLO_POST, post_code=post.post_code))


@bp.route('/gif-search', methods=("POST",))
def gif_search():
    search_term = request.form.get("searchTerm")
    post_code = request.form.get("postCode")
    search_term = bleach.clean(search_term)
    gifs = search_tenor_gifs(search_term, limit=_default_limit())
    html = render_template(
        'bombadillo/tenor_gif_search.html',
        gifs=gifs,
        post_code=post_code
    )
    return {'html': html}


@bp.route('/create', methods=('GET', 'POST'))
def create():
    """
    Creates a thread, a thread is an image, title and textbox
    """
    if request.method == 'POST':
        title = request.form.get('title')
        title = bleach.clean(title)
        gif_search = request.form.get("gifSearch")
        gif = request.form.get("gif", False)
        tenor_gif = True if gif else False
        if not gif:
            success, upload, unique_filename = _process_request_file(request)
            if not success:
                flash(current_app.config['FILE_TYPE_UNSUPPORTED'])
                return redirect(url_for('bombadillo.create'))
        else:
            unique_filename = gif
            upload = gif_search
        if (title.isspace() or title.strip() == "") and unique_filename is None:
            flash("Your post cannot be empty")
            return redirect(url_for('bombadillo.create'))
        body = ""
        processed_body = ""
        user_id = _get_current_user_id()
        post = _save_post(
            title, body, processed_body, user_id, upload, unique_filename, tenor_gif=tenor_gif, draft=False
        )
        sendgrid_notify_admin_new_post(post)
        return redirect(url_for(BOMBADILLO_POST, post_code=post.post_code))
    if g.user:
        user = g.user
    else:
        user = _get_anon_user()
    return render_template('bombadillo/create.html', user=user)


@bp.route('/save-article-draft', methods=("POST",))
def save_article_draft():
    """
    Saves a post as a draft
    """
    title = request.form.get("title")
    title = bleach.clean(title)
    body = request.form.get("editorText", "")
    body = bleach.clean(body)
    if body == "<p><br></p>":
        body = ""
    # remove all empty p tags
    body = body.replace("<p><br></p>", "")
    processed_body = body
    user_id = _get_current_user_id()
    post = _save_article(title, body, processed_body, user_id, draft=True)
    return redirect(url_for('bombadillo.edit_article_draft', post_code=post.post_code))


@bp.route('/edit-article-draft/<post_code>', methods=("GET", "POST"))
def edit_article_draft(post_code):
    """
    Edit a draft and publish
    """
    post = _get_post(post_code)
    if post.draft == False:
        flash("This post is already published")
        return redirect(url_for("bombadillo.post", post_code=post.post_code))
    user = post.user
    return render_template("bombadillo/edit_article.html", post=post, user=user)


@bp.route('/publish-article-draft/<post_code>', methods=("POST",))
def publish_article_draft(post_code):
    """
    Finalizes a Post to not be a draft any longer, visible to users
    """
    post = _get_post(post_code)
    if not g.user or g.user.id != post.user.id:
        flash("Unauthorized")
        return redirect(url_for("bombadillo.threads"))
    title = request.form.get("title")
    title = bleach.clean(title)
    body = request.form.get("editorText", "")
    body = bleach.clean(body)
    if body == "<p><br></p>":
        body = ""
    post.title = title
    post.body = body
    post.processed_body = body
    post.draft = False
    db.session.add(post)
    db.session.commit()
    return redirect(url_for(BOMBADILLO_POST, post_code=post.post_code))


@bp.route('/create-article', methods=('GET', 'POST'))
def create_article():
    """
    Creates a thread, a thread is an image, title and textbox
    """
    if request.method == 'POST':
        title = request.form.get("title")
        title = bleach.clean(title)
        body = request.form.get("editorText", "")
        body = bleach.clean(body)
        if body == "<p><br></p>":
            body = ""

app/templates/bombadillo/_create_article_form.html
<div class="pr-0 pl-0 mb-2">
    <form id="createArticleForm" method="post">
        <div class="form-group">
            <input class="form-control"
                type=text
                name="title"
                id="createArticleTitle"
                value="{{ request.form['title'] }}"
                autocomplete=off
                required
                placeholder="Title"
                onkeyup="copyArticleTitleToPreview(this.value);">
        </div>
        {% include 'bombadillo/_text_editor.html' %}
        <input class="btn btn-primary" role="button" type="button" value="Publish" onclick="submitArticleForm()">
    </form>
</div>

app/templates/bombadillo/_edit_thread_form.html
<script language="javascript">
    function increaseHeight(e){
       e.style.height = 'auto';
       var newHeight = (e.scrollHeight > 32 ? e.scrollHeight : 32);
       e.style.height = newHeight.toString() + 'px';
    }  
</script>
<div class="card exploreCard col-lg-4 pr-0 pl-0">
    <nav class="nav navbar-expand pb-2 pl-2">
        <div class="container-fluid pt-2">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{{ url_for('bombadillo.view_user', username=user.username) }}">
                        {% if user.unique_filename %}
                        <img style="height: 32px; width: 32px;"
                            src="{{ url_for('static', filename='images/{}'.format(user.unique_filename) ) }}"
                            class="rounded-circle" alt="">
                        {% else %}
                        <img style="height: 32px; width: 32px;"
                            src="{{ url_for('static', filename='images/default-profile.png') }}"
                            class="rounded-circle" alt="">
                        {% endif %}
                    </a>
                </li>
                <li class="nav-item pl-2 pt-1">
                    <span class="font-weight-normal">{{ user.username }}</span>
                </li>
            </ul>
        </div>
    </nav>
    <div class="card thread-card">
        <div class="card-body">
            <form id="createForm" action="{{ url_for('bombadillo.create_from_draft', post_code=post.post_code) }}" method="post" enctype="multipart/form-data">
                <div class="form-group mb-0">
                    <textarea class="form-control p-0 junkbiteCompose"
                        type=text
                        name="title"
                        id="junkbiteCompose"
                        autocomplete=off
                        placeholder="Whats up?"
                        rows=1
                        color="black"
                        maxlength="300"
                        onkeyup="increaseHeight(this);">{{ post.title }}</textarea>
                </div>
                {% if post.unique_filename %}
                <div id='show-image' class="mt-1">
                    <img id='load-img' alt="" src="{{ url_for('static', filename='images/{}'.format(post.unique_filename)) }}" />
                </div>
                {% endif %}
                <div id='show-image' class="mt-1">
                    <video id='load-video' style="display: none;" controls autoplay muted loop>
                        <source id=source-me type='video/webm'>
                        <source id=source-me type='video/mp4'>
                            <source id=source-me type='video/mov'>
                    </video>
                    <img id='load-img' style="display: none;" alt="" />
                </div>
                <br>
                <div class="row">
                    <input class="col" type="file" class="form-control-file" name="file" id="getval"/>
                    <button class="col-3 btn btn-primary mr-3" role="button" onclick="submitCreateForm()">Send</button>
                </div>
            </form>
        </div>
    </div>
</div>

app/templates/bombadillo/_explore_card_button_actions.html
<span class="icon-action-button pr-1" onclick="likePost('{{ post.post_code }}')">
    {% if not post.liked %}
    <svg id="heart-unfilled{{ post.post_code }}" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
        <path d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
    </svg>
    <svg id="heart-filled{{ post.post_code }}" style="display: none;" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="red" class="bi bi-heart-fill" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
    </svg>
    {% else %}
    <svg id="heart-unfilled{{ post.post_code }}" style="display: none;" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
        <path d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
    </svg>
    <svg id="heart-filled{{ post.post_code }}" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="red" class="bi bi-heart-fill" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
    </svg>
    {% endif %}
</span>
<a class="text-warning" href="{{ url_for('bombadillo.post_likes', post_code=post.post_code) }}">
    {% if post.like_count == 0 %}
    <small class="text-warning" id="likeCount{{ post.post_code }}"></small>
    {% elif post.like_count == 1 %}
    <small class="text-warning" id="likeCount{{ post.post_code }}">{{ post.like_count }} Like</small>
    {% else %}
    <small class="text-warning" id="likeCount{{ post.post_code }}">{{ post.like_count }} Likes</small>
    {% endif %}
</a>
<span class="icon-action-button pr-1" onclick="toggleThreadZap('{{ post.post_code }}')">
    {% if not post.zapped %}
    <svg id="lightning-unfilled{{ post.post_code }}" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-lightning-charge" viewBox="0 0 16 16">
        <path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09zM4.157 8.5H7a.5.5 0 0 1 .478.647L6.11 13.59l5.732-6.09H9a.5.5 0 0 1-.478-.647L9.89 2.41 4.157 8.5z"/>
    </svg>
    <svg id="lightning-filled{{ post.post_code }}" style="display: none;" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="purple" class="bi bi-lightning-charge-fill" viewBox="0 0 16 16">
        <path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
    </svg>
    {% else %}
    <svg id="lightning-unfilled{{ post.post_code }}" style="display: none;" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-lightning-charge" viewBox="0 0 16 16">
        <path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
    </svg>
    <svg id="lightning-filled{{ post.post_code }}" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="purple" class="bi bi-lightning-charge-fill" viewBox="0 0 16 16">
        <path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
    </svg>
    {% endif %}
</span>
<a class="text-warning" href="{{ url_for('bombadillo.post_zaps', post_code=post.post_code) }}">
    {% if post.sats_boosted == 0 %}
    <small class="text-warning pr-1" id="satsAmount{{ post.post_code }}"></small>
    {% elif post.sats_boosted == 1 %}
    <small class="text-warning pr-1" id="satsAmount{{ post.post_code }}">{{ post.sats_boosted }} Sat</small>
    {% else %}
    <small class="text-warning pr-1" id="satsAmount{{ post.post_code }}">{{ post.sats_boosted }} Sats</small>
    {% endif %}
</a>
{% if g.user %}
<span class="icon-action-button pl-1 pr-1" onclick="toggleCommentForm('{{ post.post_code }}')">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
        <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"/>
        </svg>
</span>
{% else %}
<span class="icon-action-button pl-1 pr-1" onclick="toggleCommentNotLoggedInForm('{{ post.post_code }}')">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
        <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"/>
        </svg>
</span>
{% endif %}
{% if post.comment_count > 0 %}
    <small class="text-warning" id="commentCount{{ post.post_code }}">{{ post.comment_count }}</small>
{% endif %}
<div class="float-right">
    <a class="icon-action-button" style="color: black; text-decoration: none;" id="viewMorePost{{ post.post_code }}" href="{{ url_for('bombadillo.post', post_code=post.post_code) }}">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-file-richtext" viewBox="0 0 16 16">
            <path d="M7 4.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0zm-.861 1.542 1.33.886 1.854-1.855a.25.25 0 0 1 .289-.047l1.888.974V7.5a.5.5 0 0 1-.5.5H5a.5.5 0 0 1-.5-.5V7s1.54-1.274 1.639-1.208zM5 9a.5.5 0 0 0 0 1h6a.5.5 0 0 0 0-1H5zm0 2a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1H5z"/>
            <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
        </svg>
    </a>
    {% if g.user and request.endpoint == 'bombadillo.post' %}
    <span class="icon-action-button" id="bookmarkPost{{ post.post_code }}" onclick="bookmarkPost('{{ post.post_code }}')">
        {% if not post.bookmarked %}
        <svg id="bookmarked{{ post.post_code }}" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-bookmark" viewBox="0 0 16 16">
            <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/>
        </svg>
        <svg id="notBookmarked{{ post.post_code }}" style="display: none;" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-bookmark-check-fill" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M2 15.5V2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.74.439L8 13.069l-5.26 2.87A.5.5 0 0 1 2 15.5zm8.854-9.646a.5.5 0 0 0-.708-.708L7.5 7.793 6.354 6.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z"/>
        </svg>
        {% else %}
        <svg id="bookmarked{{ post.post_code }}" style="display: none;" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-bookmark" viewBox="0 0 16 16">
            <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/>
        </svg>
        <svg id="notBookmarked{{ post.post_code }}" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-bookmark-check-fill" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M2 15.5V2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.74.439L8 13.069l-5.26 2.87A.5.5 0 0 1 2 15.5zm8.854-9.646a.5.5 0 0 0-.708-.708L7.5 7.793 6.354 6.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z"/>
        </svg>
        {% endif %}
    </span>
    {% endif %}
</div>

app/templates/bombadillo/_explore_card_content.html
{% if post.article %}
    {% include 'bombadillo/_explore_article_card.html' %}
{% else %}
    {% if not post.meme %}
        {% if post.unique_filename %}
            <div class="thread-card">
                {{ post.unique_filename }}
                {% if (not post.unique_filename.endswith(".webm") and not post.unique_filename.endswith(".mp4") and not post.unique_filename.endswith(".mov")) %}
                    <img src="{{ url_for('static', filename='images/{}'.format(post.unique_filename)) }}" alt=""/>
                {% else %}
                    <video autoplay muted loop controls
                        src="{{ url_for('static', filename='images/{}'.format(post.unique_filename)) }}">
                    </video>
                {% endif %}
            </div>
        {% endif %}
    {% else %}
        {% include 'bombadillo/_explore_meme_card.html' %}
    {% endif %}
{% endif %}

app/templates/bombadillo/_post_image_actions.html
<div>
    <a href="{{ url_for('static', filename='images/{}'.format(post.unique_filename)) }}">download</a>
</div>

app/templates/bombadillo/create_article.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-8 offset-md-2">
    <h3 class="text-muted">Write an Article</h3>
    <div class="card p-3" id="create-post">
        <div id="createPostAlert" style="display: none;" class="alert alert-primary" role="alert"></div>
        {% include 'bombadillo/_create_article_form.html' %}
        <div>
            <a class="mr-4" href="{{ url_for('bombadillo.create') }}">Create a Regular Post</a>
            <a class="look-like-a-link" onclick="saveArticleDraft(`{{ url_for('bombadillo.save_article_draft') }}`)">Save as Draft</a>
        </div>
    </div>
    <hr>
    <div class="previewArticle card pl-3 pt-4 pr-3">
        <h3 id="previewHeader" class="text-muted"></h3>
        <hr>
        <div id="previewBody"></div>
    </div>
</div>
{% endblock %}

app/templates/bombadillo/home.html
{% extends 'base.html' %}

{% block content %}
<div id="homeContainer">
    <div class="col-lg-6 offset-lg-3 threads-column">
        {% for post in posts %}
            {% include 'bombadillo/_explore_card.html' %}
        {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/bombadillo/notifications.html
{% extends 'base.html' %}

{% block header %}<h4 class="text-muted">Notifications</h4>{% endblock %}

{% block content %}
<div class="pb-3">
    <form method="post" action="{{ url_for('bombadillo.notifications', username=g.user.username) }}" enctype="multipart/form-data">
        <div class="form-group">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="opt out" name="markAllRead" id="markAllRead">
                <label class="form-check-label" for="markAllRead">Check the box to mark all notifications as read</label>
            </div>
        </div>
        <input class="btn btn-primary" role="button" type=submit value="Mark all as read">
    </form>
</div>

<div id="notificationsContainer">
    {% for notification in notifications %}
        {% include 'bombadillo/_notification_item.html' %}
    {% endfor %}
</div>
{% endblock %}